services:
  note_frontend:
    image: kingslayerone/note-taker-app-frontend:latest
    container_name: note_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:6000"
    environment:
      # Override the BACKEND_URL to point to the backend container directly via Docker network
      - BACKEND_URL=http://note_backend:8000
    depends_on:
      - note_backend
    networks:
      - note_network

  note_backend:
    image: kingslayerone/note-taker-app-backend:latest
    container_name: note_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - note_network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - note_backend
      - note_frontend
    restart: unless-stopped
    networks:
     - note_network 

networks:
  note_network:
    driver: bridge
